// Generated by andromda-jsf cartridge (view\table\table.component.impl.ts.vsl)
import { Component, Injector } from '@angular/core';
import { SearchMenuSectionsMenuSectionsComponent } from '@app/view/menu/search-menu-sections-menu-sections.component';

@Component({
  selector: 'search-menu-sections-menu-sections',
  templateUrl: './search-menu-sections-menu-sections.component.html',
  styleUrls: ['./search-menu-sections-menu-sections.component.scss'],
})
export class SearchMenuSectionsMenuSectionsComponentImpl extends SearchMenuSectionsMenuSectionsComponent {
  constructor(private injector: Injector) {
    super(injector);
  }

  override doSearchMenuSectionsEdit(form: any): any {
    return form;
  }
}
