// Generated by andromda-angular cartridge (app\usecase\state.store.ts.vsl) DO NOT EDIT
import { SectorVO } from '@app/model/bw/org/bocra/portal/sector/sector-vo';

export const sectorKey = "sector";

export interface SectorState {
    criteria: String | any,
    id: number | any,
    sectors: Array<SectorVO> | Array<any>,
    sector: SectorVO | any,
    loading: boolean,
    success: boolean,
    removed: boolean;
    errors: any[]
}

export const initialState: SectorState = {
    criteria: null,
    id: null,
    sectors: [],
    sector: null,
    loading: false,
    success: false,
    removed: false,
    errors: []
};