// Generated by andromda-angular cartridge (app\usecase\reducer.store.ts.vsl) DO NOT EDIT
import { Action, createFeature, createReducer, on } from '@ngrx/store';
import * as SectorActions from './sector.actions';
import {sectorKey, initialState} from './sector.state';

export const sectorReducer = createReducer(
    initialState,
    on(SectorActions.findByIdSuccess, (state, action) => ({
        ...state,
        sector: action.sector, 
        loading: false,
        success: action.success,
        errors: []
    })),
    on(SectorActions.saveSuccess, (state, action) => ({
        ...state,
        sector: action.sector, 
        loading: false,
        success: action.success,
        errors: []
    })),
    on(SectorActions.removeSuccess, (state, action) => ({
        ...state,
        removed: action.removed, 
        loading: false,
        success: action.success,
        errors: []
    })),
    on(SectorActions.getAllSuccess, (state, action) => ({
        ...state,
        sectors: action.sectors, 
        loading: false,
        success: action.success,
        errors: []
    })),
    on(SectorActions.searchSuccess, (state, action) => ({
        ...state,
        sectors: action.sectors, 
        loading: false,
        success: action.success,
        errors: []
    })),
    on(SectorActions.getAllPagedSuccess, (state, action) => ({
        ...state,
        sectors: action.sectors, 
        loading: false,
        success: action.success,
        errors: []
    })),
    on(SectorActions.sectorReset, (state) => ({
      ...state,
        criteria: null, 
        id: null, 
        sectors: [], 
        sector: null, 
        loading: false,
        success: false,
        removed: false,
        errors: []
    })),
    on(SectorActions.sectorFailure, (state, action) => ({
        ...state,
        loading: false,
        success: false,
        errors: action.errors
    })),
    on(SectorActions.sectorLoading, (state, action) => ({
        ...state,
        loading: action.loading,
        success: false
    }))
);

export const sectorFeature = createFeature({
    name: sectorKey,
    reducer: sectorReducer
});
