// license-header java merge-point
//
/**
 * @author Generated by Service.vsl in andromda-java-cartridge on 02/01/2023 19:23:09+0200 Do not modify by hand!
 *
 * TEMPLATE:     Service.vsl in andromda-java-cartridge.
 * MODEL CLASS:  bocraportal::backend::bw.org.bocra.portal::message::BocraMesssageService
 * STEREOTYPE:   Service
 */
package bw.org.bocra.portal.message;

import java.time.LocalDateTime;
import java.util.Collection;

/**
 * TODO: Model Documentation for
 * bw.org.bocra.portal.message.BocraMesssageService
 */
public interface BocraMesssageService {
     /**
      * TODO: Model Documentation for
      * bw.org.bocra.portal.message.BocraMesssageService.findById
      * 
      * @param id TODO: Model Documentation for
      *           bw.org.bocra.portal.message.BocraMesssageService.findById(id)
      * @return BocraMesssageVO
      */
     public BocraMesssageVO findById(Long id);

     /**
      * TODO: Model Documentation for
      * bw.org.bocra.portal.message.BocraMesssageService.getAll
      * 
      * @return Collection<BocraMesssageVO>
      */
     public Collection<BocraMesssageVO> getAll();

     /**
      * TODO: Model Documentation for
      * bw.org.bocra.portal.message.BocraMesssageService.getAll
      * 
      * @param pageNumber TODO: Model Documentation for
      *                   bw.org.bocra.portal.message.BocraMesssageService.getAll(pageNumber)
      * @param pageSize   TODO: Model Documentation for
      *                   bw.org.bocra.portal.message.BocraMesssageService.getAll(pageSize)
      * @return Collection<BocraMesssageVO>
      */
     public Collection<BocraMesssageVO> getAll(Integer pageNumber, Integer pageSize);

     /**
      * TODO: Model Documentation for
      * bw.org.bocra.portal.message.BocraMesssageService.remove
      * 
      * @param id TODO: Model Documentation for
      *           bw.org.bocra.portal.message.BocraMesssageService.remove(id)
      * @return boolean
      */
     public boolean remove(Long id);

     /**
      * TODO: Model Documentation for
      * bw.org.bocra.portal.message.BocraMesssageService.save
      * 
      * @param BocraMesssage TODO: Model Documentation for
      *                      bw.org.bocra.portal.message.BocraMesssageService.save(BocraMesssage)
      * @return BocraMesssageVO
      */
     public BocraMesssageVO save(BocraMesssageVO BocraMesssage);

     /**
      * TODO: Model Documentation for
      * bw.org.bocra.portal.message.BocraMesssageService.search
      * 
      * @param criteria TODO: Model Documentation for
      *                 bw.org.bocra.portal.message.BocraMesssageService.search(criteria)
      * @return Collection<BocraMesssageVO>
      */
     public Collection<BocraMesssageVO> search(String criteria);

     /**
      * TODO: Model Documentation for
      * bw.org.bocra.portal.message.BocraMesssageService.search
      * 
      * @param pageNumber TODO: Model Documentation for
      *                   bw.org.bocra.portal.message.BocraMesssageService.search(pageNumber)
      * @param pageSize   TODO: Model Documentation for
      *                   bw.org.bocra.portal.message.BocraMesssageService.search(pageSize)
      * @param criteria   TODO: Model Documentation for
      *                   bw.org.bocra.portal.message.BocraMesssageService.search(criteria)
      * @return Collection<BocraMesssageVO>
      */
     public Collection<BocraMesssageVO> search(Integer pageNumber, Integer pageSize, String criteria);

     /**
      * TODO: Model Documentation for
      * bw.org.bocra.portal.message.BocraMesssageService.loadTodayMessages
      * 
      * @return Collection<BocraMesssageVO>
      */
     public Collection<BocraMesssageVO> loadTodayMessages();

     /**
      * TODO: Model Documentation for
      * bw.org.bocra.portal.message.BocraMesssageService.clearSentMessages
      * 
      * @return Integer
      */
     public Integer clearSentMessages();

     /**
      * TODO: Model Documentation for
      * bw.org.bocra.portal.message.BocraMesssageService.clearFailedMessages
      * 
      * @return Integer
      */
     public Integer clearFailedMessages();

     /**
      * TODO: Model Documentation for
      * bw.org.bocra.portal.message.BocraMesssageService.loadDueSubmissionMessages
      * 
      * @return Collection<BocraMesssageVO>
      */
     public Collection<BocraMesssageVO> loadDueSubmissionMessages();

     /**
      * TODO: Model Documentation for
      * bw.org.bocra.portal.message.BocraMesssageService.updateMessageStatus
      * 
      * @param id     TODO: Model Documentation for
      *               bw.org.bocra.portal.message.BocraMesssageService.updateMessageStatus(id)
      * @param status TODO: Model Documentation for
      *               bw.org.bocra.portal.message.BocraMesssageService.updateMessageStatus(status)
      * @return Boolean
      */
     public Boolean updateMessageStatus(Long id, BocraMesssageStatus status);

}