// Generated by andromda-angular cartridge (app\usecase\reducer.store.ts.vsl) DO NOT EDIT
import { Action, createFeature, createReducer, on } from '@ngrx/store';
import * as DashboardActions from './dashboard.actions';
import {dashboardKey, initialState} from './dashboard.state';

export const dashboardReducer = createReducer(
    initialState,
    on(DashboardActions.dashboardReset, (state) => ({
      ...state,
        error: null
    })),
    on(DashboardActions.dashboardFailure, (state, action) => ({
        ...state,
        error: action.error
    }))
);

export const dashboardFeature = createFeature({
    name: dashboardKey,
    reducer: dashboardReducer
});
