// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, Injector } from '@angular/core';
import { HttpClient} from '@angular/common/http';
import { Observable } from 'rxjs';
import { LicenseeRestController } from '@app/service/bw/org/bocra/portal/licensee/licensee-rest-controller';
import { LicenseeCriteria } from '@app/model/bw/org/bocra/portal/licensee/licensee-criteria';
import { LicenseeVO } from '@app/model/bw/org/bocra/portal/licensee/licensee-vo';

@Injectable()
export class LicenseeRestControllerImpl extends LicenseeRestController {

    constructor(private injector: Injector) {
        super(injector);
    }

    public findById(id: number): Observable<LicenseeVO> {

        return this.http.get<LicenseeVO>(this.path + `/id/${id}`);

    }

    public getAll(): Observable<LicenseeVO[]> {

        return this.http.get<LicenseeVO[]>(this.path + `/all`);

    }

    public remove(id: number): Observable<boolean> {

        return this.http.delete<boolean>(this.path + `/id/${id}`);

    }

    public save(licenseeVO: LicenseeVO): Observable<LicenseeVO> {

        return this.http.post<LicenseeVO>(this.path, licenseeVO);

    }

    public search(criteria: LicenseeCriteria): Observable<LicenseeVO[]> {

        return this.http.post<LicenseeVO[]>(this.path + `/search`, criteria);

    }

    public getAllPaged(pageNumber: number, pageSize: number): Observable<LicenseeVO[]> {
        return this.http.get<LicenseeVO[]>(this.path + `/all/pageNumber/${pageNumber}/pageSize/${pageSize}`);
      }
}