// Generated by andromda-angular cartridge (app\usecase\action.store.ts.vsl) DO NOT EDIT
import { createAction, props } from '@ngrx/store';
import { LicenseeVO } from '@app/model/bw/org/bocra/portal/licensee/licensee-vo';
import { LicenseeCriteria } from '@app/model/bw/org/bocra/portal/licensee/licensee-criteria';
import { UserVO } from '@app/model/bw/org/bocra/portal/user/user-vo';

export enum UserActionType {
    FIND_BY_ID = '[User] Find By Id',
    FIND_BY_ID_SUCCESS = '[User] Find By Id Success',
    SAVE = '[User] Save',
    SAVE_SUCCESS = '[User] Save Success',
    REMOVE = '[User] Remove',
    REMOVE_SUCCESS = '[User] Remove Success',
    GET_ALL = '[User] Get All',
    GET_ALL_SUCCESS = '[User] Get All Success',
    SEARCH_LICENSEES = '[User] Search Licensees',
    SEARCH_LICENSEES_SUCCESS = '[User] Search Licensees Success',
    GET_ALL_PAGED = '[User] Get All Paged',
    GET_ALL_PAGED_SUCCESS = '[User] Get All Paged Success',
    CREATE_USER = '[User] Create User',
    CREATE_USER_SUCCESS = '[User] Create User Success',
    UPDATE_USER_NAME = '[User] Update User Name',
    UPDATE_USER_NAME_SUCCESS = '[User] Update User Name Success',
    LOAD_USERS = '[User] Load Users',
    LOAD_USERS_SUCCESS = '[User] Load Users Success',
    USER_RESET = '[User] User Reset',
    USER_FAILURE = '[User] User Action Failure'
}

export const findById = createAction(
    UserActionType.FIND_BY_ID,
    props<{ id: number | any  }>()
);

export const findByIdSuccess = createAction(
    UserActionType.FIND_BY_ID_SUCCESS,
    props<{ licensee: LicenseeVO | any }>()
);

export const save = createAction(
    UserActionType.SAVE,
    props<{ licensee: LicenseeVO | any  }>()
);

export const saveSuccess = createAction(
    UserActionType.SAVE_SUCCESS,
    props<{ licensee: LicenseeVO | any }>()
);

export const remove = createAction(
    UserActionType.REMOVE,
    props<{ id: number | any  }>()
);

export const removeSuccess = createAction(
    UserActionType.REMOVE_SUCCESS,
    props<{ removed: boolean | any }>()
);

export const getAll = createAction(
    UserActionType.GET_ALL);

export const getAllSuccess = createAction(
    UserActionType.GET_ALL_SUCCESS,
    props<{ licensees: LicenseeVO[] | any[] }>()
);

export const searchLicensees = createAction(
    UserActionType.SEARCH_LICENSEES,
    props<{ criteria: LicenseeCriteria | any  }>()
);

export const searchLicenseesSuccess = createAction(
    UserActionType.SEARCH_LICENSEES_SUCCESS,
    props<{ licensees: LicenseeVO[] | any[] }>()
);

export const getAllPaged = createAction(
    UserActionType.GET_ALL_PAGED,
    props<{ pageNumber: number | any , pageSize: number | any  }>()
);

export const getAllPagedSuccess = createAction(
    UserActionType.GET_ALL_PAGED_SUCCESS,
    props<{ users: LicenseeVO[] | any[] }>()
);

export const createUser = createAction(
    UserActionType.CREATE_USER,
    props<{ user: UserVO | any  }>()
);

export const createUserSuccess = createAction(
    UserActionType.CREATE_USER_SUCCESS,
    props<{ user: UserVO | any }>()
);

export const updateUserName = createAction(
    UserActionType.UPDATE_USER_NAME,
    props<{ username: string | any , userId: string | any  }>()
);

export const updateUserNameSuccess = createAction(
    UserActionType.UPDATE_USER_NAME_SUCCESS,
    props<{ updated: boolean | any }>()
);

export const loadUsers = createAction(
    UserActionType.LOAD_USERS);

export const loadUsersSuccess = createAction(
    UserActionType.LOAD_USERS_SUCCESS,
    props<{ users: UserVO[] | any[] }>()
);


export const userReset = createAction(UserActionType.USER_RESET);

export const userFailure = createAction(
    UserActionType.USER_FAILURE,
    props<{ error: any }>()
);
