// Generated by andromda-angular cartridge (app\usecase\action.store.ts.vsl) DO NOT EDIT
import { createFeatureSelector, createSelector } from '@ngrx/store';

export const licenseeKey = "licensee";

export const selectLicenseeState = createFeatureSelector<LicenseeReducer.LicenseeState> (
    LicenseeReducer.licenseeKey
);
