version: "3.9"
services:
  ###############################################################################
  # Keycloak authentication server
  ###############################################################################
  keycloak:
    image: bitnami/keycloak:22.0.1
    hostname: keycloak
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    volumes:
      - ${BOCRA_DATA}/hosts:/etc/hosts
    environment:
      KEYCLOAK_ENABLE_HEALTH_ENDPOINTS: "true"
      KEYCLOAK_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_DATABASE_USER: ${POSTGRES_USER}
      KEYCLOAK_DATABASE_NAME: ${KEYCLOAK_DB}
      KEYCLOAK_DATABASE_HOST: db
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_USER}
      KC_METRICS_ENABLED: "true"
      KC_HOSTNAME: ${KEYCLOAK_DOMAIN}
      KC_PROXY: edge
      TZ: Africa/Gaborone
    networks:
      bocraportal-public:
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.bocraportal_keycloak == true
      labels:
        - "traefik.enable=true"
        # - "traefik.docker.network=bocraportal-public"
        # - "traefik.constraint-label=bocraportal-public"
        - "traefik.http.routers.keycloak-http.rule=Host(`${KEYCLOAK_DOMAIN}`)"
        - "traefik.http.routers.keycloak-http.entrypoints=web"
        - "traefik.http.routers.keycloak-http.middlewares=https-redirect"
        - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
        - "traefik.http.routers.keycloak-https.entrypoints=websecure"
        - "traefik.http.routers.keycloak-https.rule=Host(`${KEYCLOAK_DOMAIN}`)"
        - "traefik.http.routers.keycloak-https.tls=${SSL_SECURE}"
        - "traefik.http.routers.keycloak-https.tls.certresolver=le"

###############################################################################
# Networks
###############################################################################
networks:
  bocraportal-public:
    external: true
