version: "3.9"
services:
  ###############################################################################
  # Postgres database
  ###############################################################################
  db:
    hostname: db
    image: bitnami/postgresql:15
    volumes:
      - ${BOCRA_DATA}/db:/bitnami/postgresql
      # - ${BOCRA_DATA}/postgres-conf:/opt/bitnami/postgresql/conf
    environment:
      POSTGRESQL_BOCRAPORTAL_CONNECTION_LIMIT: 500
      POSTGRESQL_USERNAME_CONNECTION_LIMIT: 500
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
      TZ: Africa/Gaborone
    # depends_on:
    #   proxy:
    #     condition: service_healthy
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD", "/opt/bitnami/postgresql/bin/pg_isready", "--username=postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      bocraportal-public:
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.bocraportal_db == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=bocraportal-public"
        - "traefik.tcp.routers.bocra-db.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.bocra-db.entrypoints=postgres"
        - "traefik.tcp.services.bocra-db.loadbalancer.server.port=5432"
        - "traefik.tcp.routers.bocra-db.tls=true"

  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://bocraportal:Cash8Aes@db:5432/bocraportal?sslmode=disable"
      # - DATA_SOURCE_USER=bocraportal
      # - DATA_SOURCE_PASS=Cash8Aes
    ports:
      - 9187:9187
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.bocraportal_db == true
    networks:
      bocraportal-public:

  ###############################################################################
  # Postgres administration frontend
  ###############################################################################
  pgadmin:
    hostname: pgadmin
    image: dpage/pgadmin4:6.18
    networks:
      bocraportal-public:
    # depends_on:
      # proxy:
      #   condition: service_healthy
      # db:
      #  condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      SCRIPT_NAME: /pgadmin
      TZ: Africa/Gaborone
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.bocraportal_db == true
      labels:
        - "traefik.enable=true"
        # - "traefik.docker.network=bocraportal-public"
        # - "traefik.constraint-label=bocra_db"
        - "traefik.http.routers.bocra-pgadmin-http.rule=Host(`${DB_DOMAIN}`) && PathPrefix(`/pgadmin`)"
        - "traefik.http.routers.bocra-pgadmin-http.entrypoints=web"
        - "traefik.http.routers.bocra-pgadmin-http.middlewares=https-redirect"
        - "traefik.http.services.bocra-pgadmin.loadbalancer.server.port=80"
        - "traefik.http.routers.bocra-pgadmin-https.entrypoints=websecure"
        - "traefik.http.routers.bocra-pgadmin-https.rule=Host(`${DB_DOMAIN}`) && PathPrefix(`/pgadmin`)"
        - "traefik.http.routers.bocra-pgadmin-https.tls=true"
        # - "traefik.http.routers.bocra-pgadmin-https.tls.certresolver=le"

###############################################################################
# Networks
###############################################################################
networks:
  bocraportal-public:
    external: true
