version: "3.9"
services:
  ###############################################################################
  # Angular web application
  ###############################################################################
  web:
    image: "bocra-web:latest"
    hostname: web

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    build:
      context: .
      dockerfile: bocraportal/angular/Dockerfile
    container_name: bocra-web
    volumes:
      - ${BOCRA_DATA}/web:/web
    depends_on:
      # db:
      #   condition: service_healthy
      # keycloak:
      #   condition: service_healthy
      api:
        condition: service_healthy
    #ports:
      #   - ${WEB_PUBLIC_PORT}:80
    networks:
      traefik-public:
      bocra-network:
        ipv4_address: ${BOCRA_WEB_ADDRESS}
      default:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bocra-web.entrypoints=websecure"
      - "traefik.http.routers.bocra-web.rule=Host(`${WEB_DOMAIN}`)"
      - "traefik.http.routers.bocra-web.tls=true"
      - "traefik.http.routers.bocra-web.tls.certresolver=le"

  ###############################################################################
  # The main API 
  ###############################################################################
  api:
    image: "bocra-api:latest"
    container_name: bocra-api
    hostname: api

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${API_SERVER_PORT}/swagger-ui.html"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    # depends_on:
      # db:
      #   condition: service_healthy
      # keycloak:
      #   condition: service_healthy
    build:
      context: .
      dockerfile: bocraportal/webservice/Dockerfile
    networks:
      bocra-network:
        ipv4_address: ${BOCRA_API_ADDRESS}
      traefik-public:
      default:
    environment:
      POSTGRES_SERVER: ${BOCRA_DB_ADDRESS}
      SERVER_PORT: ${API_SERVER_PORT}
      POSTGRES_SERVER_PORT: ${POSTGRES_SERVER_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      KEYCLOAK_AUTH_URL: ${KEYCLOAK_AUTH_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=le"
###############################################################################
# Networks
###############################################################################
networks:
  traefik-public:
  bocra-network: