version: "3.9"
services:
  ###############################################################################
  # Postgres database
  ###############################################################################
  db:
    hostname: db
    image: postgres:14
    volumes:
      - ${BOCRA_DATA}/db:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # depends_on:
    #   proxy:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      traefik-public:
      bocra-db:
        ipv4_address: ${BOCRA_DB_ADDRESS}
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.bocra_db == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.bocra-db.entrypoints=${ACTIVE_ROUTER_ENTRY}"
        - "traefik.http.routers.bocra-db.rule=Host(`${DB_DOMAIN}`)"
        - "traefik.http.routers.bocra-db.tls=${SSL_SECURE}"
        - "traefik.http.routers.bocra-db.tls.certresolver=le"
        - "traefik.http.services.bocra-db.loadbalancer.server.port=5432"

  ###############################################################################
  # Postgres administration frontend
  ###############################################################################
  pgadmin:
    hostname: pgadmin
    image: dpage/pgadmin4:6.12
    networks:
      traefik-public:
      bocra-db:
        ipv4_address: ${BOCRA_PGADMIN_ADDRESS}
    # depends_on:
      # proxy:
      #   condition: service_healthy
      # db:
      #  condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      SCRIPT_NAME: /pgadmin
      TZ: Africa/Gaborone
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.bocra_db == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.services.bocra-pgadmin.loadbalancer.server.port=80"
        - "traefik.http.routers.bocra-pgadmin.entrypoints=${ACTIVE_ROUTER_ENTRY}"
        - "traefik.http.routers.bocra-pgadmin.rule=Host(`${DB_DOMAIN}`) && PathPrefix(`/pgadmin`)"
        - "traefik.http.routers.bocra-pgadmin.tls=${SSL_SECURE}"
        - "traefik.http.routers.bocra-pgadmin.tls.certresolver=le"

###############################################################################
# Networks
###############################################################################
networks:
  traefik-public:
    external: true
  bocra-db:
    name: bocra-db
    driver: overlay
    external: false
    ipam:
      driver: default
      config:
        - subnet: 192.168.57.0/24