version: "3.9"
services:
  ###############################################################################
  # Keycloak authentication server
  ###############################################################################
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2-legacy
    hostname: keycloak
    #container_name: bocra-keycloak
    restart: unless-stopped
    command: ["-b", "0.0.0.0","-Dkeycloak.profile.feature.docker=enabled"]
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/auth/realms/master"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: POSTGRES
      DB_ADDR: ${POSTGRES_SERVER}
      DB_DATABASE: ${KEYCLOAK_DB}
      DB_USER: ${POSTGRES_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_PROXY: edge
      KEYCLOAK_LOGLEVEL: DEBUG
      JDBC_PARAMS=useSSL: true
      GROUPS_DISCOVERY_PROTOCOL: JDBC_PING
    depends_on:
      db:
        condition: service_healthy
    networks:
      traefik-public:
      bocra-network:
        ipv4_address: ${BOCRA_KEYCLOAK_ADDRESS}
      default:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_DOMAIN}`)"
      - "traefik.http.services.keycloak.loadbalancer.passhostheader=true"
      - "traefik.http.routers.keycloak.service=keycloak"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.routers.keycloak.tls.certresolver=le"
###############################################################################
# Networks
###############################################################################
networks:
  traefik-public:
  bocra-network: