version: "3.9"
services:
  ###############################################################################
  # Rabbit MQ
  ###############################################################################
  rabbitmq:
    image: rabbitmq:management
    container_name: bocraportal-rabbitmq
    hostname: rabbitmq
    # volumes:
    #  - ${BOCRA_DATA}/rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      TZ: Africa/Gaborone
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      traefik-public:
      default:
    ports:
      - "${RABBITMQ_SERVICE_PORT}:${RABBITMQ_SERVICE_PORT}"
      - "${RABBITMQ_WEB_PORT}:${RABBITMQ_WEB_PORT}"
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.bocraportal_rabbitmq == true
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbitmq-web.rule=Host(`${RABBIT_DOMAIN}`)"
        - "traefik.http.routers.rabbitmq-web.entrypoints=web"
        - "traefik.http.routers.rabbitmq-web.middlewares=https-redirect"
        - "traefik.http.routers.rabbitmq-websecure.entrypoints=websecure"
        - "traefik.http.routers.rabbitmq-websecure.rule=Host(`${RABBIT_DOMAIN}`)"
        - "traefik.http.routers.rabbitmq-websecure.tls=${SSL_SECURE}"
        - "traefik.tcp.routers.rabbitmq-ingress.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.rabbitmq-ingress.entrypoints=rabbitmq"
        - "traefik.tcp.services.rabbitmq-ingress.loadbalancer.server.port=5672"

###############################################################################
# Networks
###############################################################################
networks:
  traefik-public:
    external: true