// Generated by andromda-angular cartridge (app\usecase\reducer.store.ts.vsl) DO NOT EDIT
import { Action, createFeature, createReducer, on } from '@ngrx/store';
import * as DataProcessingActions from './data-processing.actions';
import {dataProcessingKey, initialState} from './data-processing.state';

export const dataProcessingReducer = createReducer(
    initialState,
    on(DataProcessingActions.findByIdSuccess, (state, action) => ({
        ...state,
        submissions: [], 
        loading: false,
        success: action.success,
        messages: action.messages
    })),
    on(DataProcessingActions.saveSuccess, (state, action) => ({
        ...state,
        submissions: [], 
        loading: false,
        success: action.success,
        messages: action.messages
    })),
    on(DataProcessingActions.removeSuccess, (state, action) => ({
        ...state,
        submissions: [], 
        loading: false,
        success: action.success,
        messages: action.messages
    })),
    on(DataProcessingActions.getAllSuccess, (state, action) => ({
        ...state,
        submissions: [], 
        loading: false,
        success: action.success,
        messages: action.messages
    })),
    on(DataProcessingActions.searchSuccess, (state, action) => ({
        ...state,
        submissions: [], 
        loading: false,
        success: action.success,
        messages: action.messages
    })),
    on(DataProcessingActions.getAllPagedSuccess, (state, action) => ({
        ...state,
        submissions: [], 
        loading: false,
        success: action.success,
        messages: action.messages
    })),
    on(DataProcessingActions.addDataFieldsSuccess, (state, action) => ({
        ...state,
        submissions: [], 
        loading: false,
        success: action.success,
        messages: action.messages
    })),
    on(DataProcessingActions.addDataFieldSuccess, (state, action) => ({
        ...state,
        submissions: [], 
        loading: false,
        success: action.success,
        messages: action.messages
    })),
    on(DataProcessingActions.deleteDataFieldSuccess, (state, action) => ({
        ...state,
        submissions: [], 
        loading: false,
        success: action.success,
        messages: action.messages
    })),
    on(DataProcessingActions.dataProcessingReset, (state) => ({
      ...state,
        submissions: [], 
        loading: false,
        success: false,
        error: false,
        messges: []
    })),
    on(DataProcessingActions.dataProcessingFailure, (state, action) => ({
        ...state,
        loading: false,
        success: false,
        error: true,
        messages: action.messages
    })),
    on(DataProcessingActions.dataProcessingLoading, (state, action) => ({
        ...state,
        loading: action.loading,
        success: false
    }))
);

export const dataProcessingFeature = createFeature({
    name: dataProcessingKey,
    reducer: dataProcessingReducer
});
