// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWS.java.vsl in andromda-webservices. Do not modify by hand!.
//
package bw.org.bocra.portal.period.config;

import java.util.Collection;

import org.junit.ClassRule;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.ResponseEntity;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.testcontainers.containers.PostgreSQLContainer;

import com.fasterxml.jackson.databind.ObjectMapper;

import bw.org.bocra.portal.BocraportalTestContainer;
import bw.org.bocra.portal.GenericRestTest;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@RunWith(SpringRunner.class)
@AutoConfigureMockMvc
public class PeriodConfigRestControllerTest extends GenericRestTest<PeriodConfigVO, PeriodConfigCriteria> {

    @ClassRule
    public static PostgreSQLContainer postgreSQLContainer = BocraportalTestContainer.getInstance();

    private String path = "/period/config";

    protected Logger logger = LoggerFactory.getLogger(PeriodConfigRestControllerTest.class);

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private PeriodConfigRestController periodConfigRestController;

    @Autowired
    protected PeriodConfigService periodConfigService;

    @BeforeEach
    public void clean() {
    }

    @WithMockUser(username = "testuser4", password = "testuser1")
    @Test
    public void findById() {

    }

    @WithMockUser(username = "testuser4", password = "testuser1")
    @Test
    public void getAll() {

    }

    @WithMockUser(username = "testuser4", password = "testuser1")
    @Test
    public void getAllPaged() {

    }

    @WithMockUser(username = "testuser4", password = "testuser1")
    @Test
    public void remove() {

    }

    @WithMockUser(username = "testuser4", password = "testuser1")
    @Test
    public void save() {

    }

    @WithMockUser(username = "testuser4", password = "testuser1")
    @Test
    public void search() {

    }

    @Override
    protected Collection<PeriodConfigVO> dummyData(int num) {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    protected PeriodConfigVO unsavedDummyData() {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    protected ResponseEntity<?> handleGetAll() {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    protected ResponseEntity<?> handleGetAllPaged(int pageNumber, int pageSize) {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    protected ResponseEntity<?> handleFindById(Long id) {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    protected ResponseEntity<?> handleRemove(Long id) {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    protected ResponseEntity<?> handleSearch(PeriodConfigCriteria criteria) {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    protected ResponseEntity<?> handlePagedSearch(int pagenumber, int pageSize, PeriodConfigCriteria criteria) {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    protected ResponseEntity<?> handleSave(PeriodConfigVO o) {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    protected void basicCompareAssertions(PeriodConfigVO o1, PeriodConfigVO o2) {
        // TODO Auto-generated method stub
        
    }

    @Override
    protected Collection<PeriodConfigVO> searchData() {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    protected PeriodConfigCriteria searchCriteria() {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    protected PeriodConfigCriteria searchCriteriaNone() {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    protected PeriodConfigCriteria searchCriteriaEmpty() {
        // TODO Auto-generated method stub
        return null;
    }

}