// Generated by andromda-angular cartridge (app\usecase\state.store.ts.vsl) DO NOT EDIT
import { LicenseTypeCriteria } from '@app/model/bw/org/bocra/portal/type/license-type-criteria';
import { LicenseTypeVO } from '@app/model/bw/org/bocra/portal/type/license-type-vo';

export const licenseTypeKey = "licenseType";

export interface LicenseTypeState {
    id: number | any,
    licenseType: LicenseTypeVO | any,
    licenseTypes: Array<LicenseTypeVO> | Array<any>,
    searchCriteria: LicenseTypeCriteria | any,
    removed: boolean,
    error: any
}

export const initialState: LicenseTypeState = {
    id: null,
    licenseType: null,
    licenseTypes: [],
    searchCriteria: null,
    removed: false,
    error: null
};