// Generated by andromda-angular cartridge (app\usecase\effect.store.ts.vsl) DO NOT EDIT
import { Injectable } from '@angular/core';
import { Actions, createEffect, ofType } from '@ngrx/effects';
import { catchError, map, mergeMap } from 'rxjs/operators';
import * as PeriodConfigActions from './period-config.action';
import { PeriodConfigRestControllerImpl } from '@app/service/bw/org/bocra/portal/period/config/period-config-rest-controller.impl';

@Injectable()
export class PeriodConfigEffects {

    constructor(private actions$: Actions, private periodConfigRestController: PeriodConfigRestControllerImpl) {}

    findById$ = createEffect(() => 
         this.actions$.pipe(
            ofType(PeriodConfigActions.findById),
            mergeMap(({ id }) => this.periodConfigRestController.findById(id).pipe(
                map( results => PeriodConfigActions.findByIdSuccess({results})),
                catchError(({error}) => [PeriodConfigActions.periodConfigFailure(error)])
            ))
        )
    );

    save$ = createEffect(() => 
         this.actions$.pipe(
            ofType(PeriodConfigActions.save),
            mergeMap(({ periodConfigVO }) => this.periodConfigRestController.save(periodConfigVO).pipe(
                map( results => PeriodConfigActions.saveSuccess({results})),
                catchError(({error}) => [PeriodConfigActions.periodConfigFailure(error)])
            ))
        )
    );

    remove$ = createEffect(() => 
         this.actions$.pipe(
            ofType(PeriodConfigActions.remove),
            mergeMap(({ id }) => this.periodConfigRestController.remove(id).pipe(
                map( results => PeriodConfigActions.removeSuccess({results})),
                catchError(({error}) => [PeriodConfigActions.periodConfigFailure(error)])
            ))
        )
    );

    getAll$ = createEffect(() => 
         this.actions$.pipe(
            ofType(PeriodConfigActions.getAll),
            mergeMap(() => this.periodConfigRestController.getAll().pipe(
                map( results => PeriodConfigActions.getAllSuccess({results})),
                catchError(({error}) => [PeriodConfigActions.periodConfigFailure(error)])
            ))
        )
    );

    search$ = createEffect(() => 
         this.actions$.pipe(
            ofType(PeriodConfigActions.search),
            mergeMap(({ searchCriteria }) => this.periodConfigRestController.search(searchCriteria).pipe(
                map( results => PeriodConfigActions.searchSuccess({results})),
                catchError(({error}) => [PeriodConfigActions.periodConfigFailure(error)])
            ))
        )
    );

    getAllPaged$ = createEffect(() => 
         this.actions$.pipe(
            ofType(PeriodConfigActions.getAllPaged),
            mergeMap(({pageNumber, pageSize}) => this.periodConfigRestController.getAllPaged(pageNumber, pageSize).pipe(
                map( results => PeriodConfigActions.getAllPagedSuccess({results})),
                catchError(({error}) => [PeriodConfigActions.periodConfigFailure(error)])
            ))
        )
    );

}
