// Generated by andromda-angular cartridge (app\usecase\state.store.ts.vsl) DO NOT EDIT

import { Menu } from "@app/model/menu/menu";

export const menuKey = 'menu';

export interface MenuState {
  menus: Menu[] | any[];
  messages: any[];
}

export const initialState: MenuState = {
  menus: [],
  messages: [],
};
