// Generated by andromda-angular cartridge (app\usecase\reducer.store.ts.vsl) DO NOT EDIT
import { Action, createFeature, createReducer, on } from '@ngrx/store';
import * as SectorActions from './sector.actions';
import {sectorKey, initialState} from './sector.state';

export const sectorReducer = createReducer(
    initialState,
    on(SectorActions.sectorReset, (state) => ({
      ...state,
        menuSection: null, 
        id: null, 
        criteria: null, 
        menuSections: [], 
        loading: false,
        success: false,
        error: false,
        messges: []
    })),
    on(SectorActions.sectorFailure, (state, action) => ({
        ...state,
        loading: false,
        success: false,
        error: true,
        messages: action.messages
    })),
    on(SectorActions.sectorLoading, (state, action) => ({
        ...state,
        loading: action.loading,
        success: false
    }))
);

export const sectorFeature = createFeature({
    name: sectorKey,
    reducer: sectorReducer
});
