// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { EditPeriodComponent } from '@app/view/period/edit-period.component';
import { EditPeriodSaveForm } from '@app/view/period/edit-period.component';
import { EditPeriodSearchForm } from '@app/view/period/edit-period.component';
import { EditPeriodDeleteForm } from '@app/view/period/edit-period.component';
import { EditPeriodVarsForm } from '@app/view/period/edit-period.component';

@Component({
  selector: 'app-edit-period',
  templateUrl: './edit-period.component.html',
  styleUrls: ['./edit-period.component.scss']
})
export class EditPeriodComponentImpl extends EditPeriodComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

    beforeOnInit(){
    }
	
    afterOnInit() {
    }

    doNgAfterViewInit() {
    }

    handleFormChanges(change: any) {
    }

    /**
     * This method may be overwritten
     */
    afterSetEditPeriodVarsForm(form: EditPeriodVarsForm): void {

    }

    /**
     * This method may be overwritten
     */
    afterSetEditPeriodSaveForm(form: EditPeriodSaveForm): void {

    }

    /**
     * This method may be overwritten
     */
    beforeEditPeriodSave(form: EditPeriodSaveForm): void {

    }

    /**
     * This method may be overwritten
     */
    afterEditPeriodSave(form: EditPeriodSaveForm): void {

    }
    
    /**
     * This method may be overwritten
     */
    afterSetEditPeriodSearchForm(form: EditPeriodSearchForm): void {

    }

    /**
     * This method may be overwritten
     */
    beforeEditPeriodSearch(form: EditPeriodSearchForm): void {

    }

    /**
     * This method may be overwritten
     */
    afterEditPeriodSearch(form: EditPeriodSearchForm): void {

    }
    
    /**
     * This method may be overwritten
     */
    afterSetEditPeriodDeleteForm(form: EditPeriodDeleteForm): void {

    }

    /**
     * This method may be overwritten
     */
    beforeEditPeriodDelete(form: EditPeriodDeleteForm): void {

    }

    /**
     * This method may be overwritten
     */
    afterEditPeriodDelete(form: EditPeriodDeleteForm): void {

    }
    
}