# Dockerfile
FROM ubuntu:22.04

ARG CERT
ARG CERT_PASSWORD

ENV CERT ${CERT}
ENV CERT_PASSWORD ${CERT_PASSWORD}

RUN mkdir -p /app
WORKDIR /app

COPY deployment/certs/${CERT}.crt /app/certs/${CERT}.crt
# RUN keytool -importcert -file /app/certs/${CERT}.crt -noprompt -alias bocra -storepass ${CERT_PASSWORD} -keystore ${JAVA_HOME}/lib/security/cacerts

ARG JAR_FILE=bocraportal/bocracron/target/bocraportal-cron
COPY ${JAR_FILE} bocraportal-cron
ENTRYPOINT ["/app/bocraportal-cron"]
EXPOSE 8099
