// Generated by andromda-angular cartridge (app\usecase\reducer.store.ts.vsl) DO NOT EDIT
import { Action, createFeature, createReducer, on } from '@ngrx/store';
import * as FormActions from './form.action';
import {formKey, initialState} from './form.state';

export const formReducer = createReducer(
    initialState,
    on(FormActions.findByIdSuccess, (state, action) => ({
        ...state,
        searchCriteria: null, 
        forms: [], 
        formVO: null, 
        id: null, 
        error: action.error
    })),
    on(FormActions.saveSuccess, (state, action) => ({
        ...state,
        searchCriteria: null, 
        forms: [], 
        formVO: null, 
        id: null, 
        error: action.error
    })),
    on(FormActions.removeSuccess, (state, action) => ({
        ...state,
        searchCriteria: null, 
        forms: [], 
        formVO: null, 
        id: null, 
        error: action.error
    })),
    on(FormActions.getAllSuccess, (state, action) => ({
        ...state,
        searchCriteria: null, 
        forms: [], 
        formVO: null, 
        id: null, 
        error: action.error
    })),
    on(FormActions.searchSuccess, (state, action) => ({
        ...state,
        searchCriteria: null, 
        forms: [], 
        formVO: null, 
        id: null, 
        error: action.error
    })),
    on(FormActions.getAllPagedSuccess, (state, action) => ({
        ...state,
        searchCriteria: null, 
        forms: [], 
        formVO: null, 
        id: null, 
        error: action.error
    })),
    on(FormActions.formReset, (state) => ({
      ...state,
        searchCriteria: null, 
        forms: [], 
        formVO: null, 
        id: null, 
        error: null
    })),
    on(FormActions.formFailure, (state, action) => ({
        ...state,
        error: action.error
    }))
);

export const formFeature = createFeature({
    name: formKey,
    reducer: formReducer
});
