// Generated by andromda-angular cartridge (app\usecase\state.store.ts.vsl) DO NOT EDIT
import { FormFieldVO } from '@app/model/bw/org/bocra/portal/form/field/form-field-vo';
import { FormCriteria } from '@app/model/bw/org/bocra/portal/form/form-criteria';
import { FormVO } from '@app/model/bw/org/bocra/portal/form/form-vo';

export const formKey = 'form';

export interface FormState {
  id: number | any;
  forms: Array<FormVO> | Array<any>;
  form: FormVO | any;
  searchCriteria: FormCriteria | any;
  removed: boolean;
  formField: FormFieldVO | any;
  error: any;
}

export const initialState: FormState = {
  id: null,
  forms: [],
  form: null,
  searchCriteria: null,
  removed: false,
  formField: null,
  error: null,
};
