// Generated by andromda-angular cartridge (app\usecase\state.store.ts.vsl) DO NOT EDIT
import { FormCriteria } from '@app/model/bw/org/bocra/portal/form/form-criteria';
import { FormVO } from '@app/model/bw/org/bocra/portal/form/form-vo';

export const formKey = "form";

export interface FormState {
    pageNumber: number | any,
    id: number | any,
    pageSize: number | any,
    criteria: FormCriteria | any,
    formVO: FormVO | any,
    forms: FormVO[] | any[],
    removed: boolean,
    error: any
}

export const initialState: FormState = {
    pageNumber: null,
    id: null,
    pageSize: null,
    criteria: null,
    formVO: null,
    forms: [],
    removed: false,
    error: null
};