// Generated by andromda-angular cartridge (app\usecase\action.store.ts.vsl) DO NOT EDIT
import { createAction, props } from '@ngrx/store';
import { UrlGuardCriteria } from '@app/model/bw/org/bocra/portal/guard/url-guard-criteria';
import { UrlGuardVO } from '@app/model/bw/org/bocra/portal/guard/url-guard-vo';

export enum GuardActionType {
    SAVE_GUARD = '[Guard] Save Guard',
    SAVE_GUARD_SUCCESS = '[Guard] Save Guard Success',
    FIND_BY_ID = '[Guard] Find By Id',
    FIND_BY_ID_SUCCESS = '[Guard] Find By Id Success',
    LOAD_ALL = '[Guard] Load All',
    LOAD_ALL_SUCCESS = '[Guard] Load All Success',
    SEARCH_GUARDS = '[Guard] Search Guards',
    SEARCH_GUARDS_SUCCESS = '[Guard] Search Guards Success',
    ACTION_FAILURE = '[Guard] Action Failure'
}

export const saveGuard = createAction(
    GuardActionType.SAVE_GUARD,
    props<{ guard: UrlGuardVO }>()
);

export const saveGuardSuccess = createAction(
    GuardActionType.SAVE_GUARD_SUCCESS,
    props<{ guard: any }>()
);

export const findById = createAction(
    GuardActionType.FIND_BY_ID,
    props<{ id: number }>()
);

export const findByIdSuccess = createAction(
    GuardActionType.FIND_BY_ID_SUCCESS,
    props<{ guard: UrlGuardVO }>()
);

export const loadAll = createAction(
    GuardActionType.LOAD_ALL
);

export const loadAllSuccess = createAction(
    GuardActionType.LOAD_ALL_SUCCESS,
    props<{ guards: UrlGuardVO[] }>()
);

export const searchGuards = createAction(
    GuardActionType.SEARCH_GUARDS,
    props<{ searchCriteria: UrlGuardCriteria }>()
);

export const searchGuardsSuccess = createAction(
    GuardActionType.SEARCH_GUARDS_SUCCESS,
    props<{ guards: UrlGuardVO[] }>()
);

export const guardActionFailure = createAction(
    GuardActionType.ACTION_FAILURE,
    props<{ error: any }>()
);