// Generated by andromda-angular cartridge (app\usecase\effect.store.ts.vsl) DO NOT EDIT
import { Injectable } from '@angular/core';
import { Actions, createEffect, ofType } from '@ngrx/effects';
import { catchError, map, mergeMap } from 'rxjs/operators';
import * as PeriodActions from './period.actions';
import { PeriodRestControllerImpl } from '@app/service/bw/org/bocra/portal/period/period-rest-controller.impl';

@Injectable()
export class PeriodEffects {

    constructor(private actions$: Actions, private periodRestController: PeriodRestControllerImpl) {}

    findById$ = createEffect(() => 
         this.actions$.pipe(
            ofType(PeriodActions.findById),
            mergeMap(({ id }) => this.periodRestController.findById(id).pipe(
                map( results => PeriodActions.findByIdSuccess({results})),
                catchError(({error}) => [PeriodActions.periodFailure(error)])
            ))
        )
    );

    save$ = createEffect(() => 
         this.actions$.pipe(
            ofType(PeriodActions.save),
            mergeMap(({ period }) => this.periodRestController.save(period).pipe(
                map( results => PeriodActions.saveSuccess({results})),
                catchError(({error}) => [PeriodActions.periodFailure(error)])
            ))
        )
    );

    remove$ = createEffect(() => 
         this.actions$.pipe(
            ofType(PeriodActions.remove),
            mergeMap(({ id }) => this.periodRestController.remove(id).pipe(
                map( results => PeriodActions.removeSuccess({results})),
                catchError(({error}) => [PeriodActions.periodFailure(error)])
            ))
        )
    );

    getAll$ = createEffect(() => 
         this.actions$.pipe(
            ofType(PeriodActions.getAll),
            mergeMap(() => this.periodRestController.getAll().pipe(
                map( results => PeriodActions.getAllSuccess({results})),
                catchError(({error}) => [PeriodActions.periodFailure(error)])
            ))
        )
    );

    search$ = createEffect(() => 
         this.actions$.pipe(
            ofType(PeriodActions.search),
            mergeMap(({ criteria }) => this.periodRestController.search(criteria).pipe(
                map( results => PeriodActions.searchSuccess({results})),
                catchError(({error}) => [PeriodActions.periodFailure(error)])
            ))
        )
    );

    getAllPaged$ = createEffect(() => 
         this.actions$.pipe(
            ofType(PeriodActions.getAllPaged),
            mergeMap(({ pageNumber, pageSize }) => this.periodRestController.getAllPaged(pageNumber, pageSize).pipe(
                map( results => PeriodActions.getAllPagedSuccess({results})),
                catchError(({error}) => [PeriodActions.periodFailure(error)])
            ))
        )
    );

}
