// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root',
})
export class ReportRestController {
  protected path = '/report';

  constructor(private http: HttpClient) {}

  public createWordDocument(data: any): Observable<any> {
    return this.http.post(`${this.path}/word`, data, { responseType: 'blob' });
  }

  public _createWordDocument(data: any, images: File[]): Observable<any> {
    
    let formData: FormData = new FormData();

    formData.append('data', JSON.stringify(data));
    images.forEach(image => {
      formData.append('images', image)
    })

    return this.http.post(`${this.path}/create/word`, formData, { responseType: 'blob' });
  }

  public createComplaintReportWordDocument(data: any): Observable<any> {
    return this.http.post(`${this.path}/complaint/word`, data, { responseType: 'blob' });
  }
}
