// Generated by andromda-angular cartridge (app\usecase\selector.store.ts.vsl) DO NOT EDIT
import { createFeatureSelector, createSelector } from '@ngrx/store';

export const userKey = "user";

export const selectUserState = createFeatureSelector<UserReducer.UserState> (
    UserReducer.userKey
);
