FROM node:16-alpine
WORKDIR /app

COPY ./bocraportal/angular/package.json .
COPY ./bocraportal/angular/target/bocraportal ./

RUN npm install -g @angular/cli
RUN npm install

ENTRYPOINT ["ng", "serve"]

#FROM nginx as runtime
#COPY --from=build /app/dist/bocraportal-web /usr/share/nginx/html