FROM node:17
WORKDIR /app

RUN npm install -g @angular/cli

COPY ./bocraportal/angular/package.json .
RUN npm install
COPY ./bocraportal/angular ./

ENTRYPOINT ["ng", "serve"]

#FROM nginx as runtime
#COPY --from=build /app/dist/bocraportal-web /usr/share/nginx/html