// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { SearchVoiceTrafficComponent } from '@app/view/form/voice/search-voice-traffic.component';
import { SearchVoiceTrafficEditForm } from '@app/view/form/voice/search-voice-traffic.component';
import { SearchVoiceTrafficSearchForm } from '@app/view/form/voice/search-voice-traffic.component';
import { SearchVoiceTrafficVarsForm } from '@app/view/form/voice/search-voice-traffic.component';

@Component({
  selector: 'app-search-voice-traffic',
  templateUrl: './search-voice-traffic.component.html',
  styleUrls: ['./search-voice-traffic.component.scss']
})
export class SearchVoiceTrafficComponentImpl extends SearchVoiceTrafficComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

    beforeOnInit(){
    }
	
    afterOnInit() {
        this.addVoiceTrafficsDummyData();
    }

    doNgAfterViewInit() {
    }

    handleFormChanges(change: any) {
    }

    /**
     * This method may be overwritten
     */
    afterSetSearchVoiceTrafficVarsForm(form: SearchVoiceTrafficVarsForm): void {

    }

    /**
     * This method may be overwritten
     */
    afterSetSearchVoiceTrafficEditForm(form: SearchVoiceTrafficEditForm): void {

    }

    /**
     * This method may be overwritten
     */
    beforeSearchVoiceTrafficEdit(form: SearchVoiceTrafficEditForm): void {

    }

    /**
     * This method may be overwritten
     */
    afterSearchVoiceTrafficEdit(form: SearchVoiceTrafficEditForm): void {

    }
    
    /**
     * This method may be overwritten
     */
    afterSetSearchVoiceTrafficSearchForm(form: SearchVoiceTrafficSearchForm): void {

    }

    /**
     * This method may be overwritten
     */
    beforeSearchVoiceTrafficSearch(form: SearchVoiceTrafficSearchForm): void {

    }

    /**
     * This method may be overwritten
     */
    afterSearchVoiceTrafficSearch(form: SearchVoiceTrafficSearchForm): void {

    }
    
}