// Generated by andromda-angular cartridge (app\usecase\action.store.ts.vsl) DO NOT EDIT
import { createFeature, createReducer, on } from '@ngrx/store';
import { KpiVO } from '@app/model/bw/org/bocra/portal/kpi/kpi-vo';
import { FormCriteria } from '@app/model/bw/org/bocra/portal/form/form-criteria';
import * as KpiActions from './kpi.action';

export const kpiKey = "kpi";

export interface KpiState {
    kpi: KpiVO;
    kpis: KpiVO[];
    searchCriteria: FormCriteria
    loading: boolean;
    id: number;
    error: any
}

export const initialState: KpiState = {
    kpi: new KpiVO,
    kpis: [],
    searchCriteria: new FormCriteria,
    loading: false,
    id: 0,
    error: null
};

export const kpiReducer = createReducer(
    initialState,
    on(KpiActions.saveKpi, (state, action) => ({
        ...state,
        kpi: action.kpi
    })),
    on(KpiActions.saveKpiSuccess, (state, action) => ({
        ...state,
        kpi: action.kpi,
        kpis: [...state.kpis, action.kpi]
    })),
    on(KpiActions.findById, (state, action) => ({
        ...state,
        id: action.id
    })),
    on(KpiActions.findByIdSuccess, (state, action) => ({
        ...state,
        kpi: action.kpi,
        kpis: [...state.kpis, action.kpi]
    })),
    on(KpiActions.loadAll, (state, action) => ({
        ...state
    })),
    on(KpiActions.loadAllSuccess, (state, action) => ({
        ...state,
        kpi: new KpiVO,
        kpis: action.kpis
    })),
    on(KpiActions.searchKpis, (state, action) => ({
        ...state,
        searchCriteria: action.searchCriteria
    })),
    on(KpiActions.searchKpisSuccess, (state, action) => ({
        ...state,
        kpi: new KpiVO,
        searchCriteria: new FormCriteria,
        kpis: action.kpis
    })),
    on(KpiActions.reset, (state) => ({
      ...state,
      kpi: new KpiVO,
      searchCriteria: new FormCriteria,
      kpis: []
    })),
    on(KpiActions.kpiActionFailure, (state, action) => ({
        ...state,
        error: action.error
    }))
);

export const kpiFeature = createFeature({
    name: kpiKey,
    reducer: kpiReducer
});
