// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringService.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.org.bocra.portal.user;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
@ExtendWith(MockitoExtension.class)
public class LicenseeUserServiceTest {

    protected Logger logger = LoggerFactory.getLogger(LicenseeUserServiceTest.class);
    
    @InjectMocks
    private LicenseeUserServiceImpl licenseeUserService;

    @Mock
    private LicenseeUserDao licenseeUserDao;

    @Mock
    private LicenseeUserRepository licenseeUserRepository;

    @Test
    public void checkInjects() {

        Assertions.assertNotNull(licenseeUserDao);
        Assertions.assertNotNull(licenseeUserRepository);
        Assertions.assertNotNull(licenseeUserService);

    }
    

    @Test
    public void findById_success() {
        
    }

    @Test
    public void findById_fail() {
        
    }


    @Test
    public void save_success() {
        
    }

    @Test
    public void save_fail() {
        
    }

    @Test
    public void save_licenseeUser_null() {
        
    }

    @Test
    public void save_LicenseeUser_User_null() {
        
    }

    @Test
    public void save_LicenseeUser_Licensee_null() {
        
    }

    @Test
    public void save_LicenseeUser_Id_null() {
        
    }

    @Test
    public void save_LicenseeUser_DateAdded_null() {
        
    }


    @Test
    public void remove_success() {
        
    }

    @Test
    public void remove_fail() {
        
    }


    @Test
    public void getAll_success() {
        
    }

    @Test
    public void getAll_fail() {
        
    }


    @Test
    public void search_success() {
        
    }

    @Test
    public void search_fail() {
        
    }

    @Test
    public void search_userId_null() {
        
    }

    @Test
    public void search_licenseeUin_null() {
        
    }

    @Test
    public void search_licenseeName_null() {
        
    }


    @Test
    public void update_success() {
        
    }

    @Test
    public void update_fail() {
        
    }

    @Test
    public void update_licenseeUser_null() {
        
    }

    @Test
    public void update_LicenseeUser_User_null() {
        
    }

    @Test
    public void update_LicenseeUser_Licensee_null() {
        
    }

    @Test
    public void update_LicenseeUser_Id_null() {
        
    }

    @Test
    public void update_LicenseeUser_DateAdded_null() {
        
    }
}