// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { SearchKPIsComponent } from '@app/view/form/kpi/search-kpis.component';
import { SearchKPIsSearchForm } from '@app/view/form/kpi/search-kpis.component';

@Component({
  selector: 'app-search-kpis',
  templateUrl: './search-kpis.component.html',
  styleUrls: ['./search-kpis.component.scss']
})
export class SearchKPIsComponentImpl extends SearchKPIsComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

    beforeOnInit(){
    }
	
    afterOnInit() {
        this.addKpisDummyData();
    }

    doNgAfterViewInit() {
    }

    handleFormChanges(change: any) {
    }

    /**
     * This method may be overwritten
     */
    afterSetSearchKPIsSearchForm(form: SearchKPIsSearchForm): void {

    }

    /**
     * This method may be overwritten
     */
    beforeSearchKPIsSearch(form: SearchKPIsSearchForm): void {

    }

    /**
     * This method may be overwritten
     */
    afterSearchKPIsSearch(form: SearchKPIsSearchForm): void {

    }
    
}