# Dockerfile
FROM eclipse-temurin:17

ARG CERT
ARG CERT_PASSWORD

RUN apt-get update

RUN mkdir -p /app
WORKDIR /app

COPY deployment/certs/${CERT}.crt /app/certs/${CERT}.crt
RUN keytool -importcert -file /app/certs/${CERT}.crt -noprompt -alias bocra -storepass ${CERT_PASSWORD} -keystore ${JAVA_HOME}/lib/security/cacerts

ARG JAR_FILE=bocraportal/comm/target/bocraportal-comm
COPY ${JAR_FILE} bocraportal-comm
ENTRYPOINT ["/app/bocraportal-comm"]
EXPOSE 8095
