// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Inject, Injector } from '@angular/core';
import { AddNewSectionVarsForm, AddNewSectionComponent } from '@app/view/form/add-new-section.component';
import { FormState } from '@app/store/form/form.state';
import * as FormSelectors from '@app/store/form/form.selectors';
import * as FormActions from '@app/store/form/form.actions';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { FormFieldVO } from '@app/model/bw/org/bocra/portal/form/field/form-field-vo';
import { FormVO } from '@app/model/bw/org/bocra/portal/form/form-vo';
import { MAT_DIALOG_DATA } from '@angular/material/dialog';

@Component({
  selector: 'app-add-new-section',
  templateUrl: './add-new-section.component.html',
  styleUrls: ['./add-new-section.component.scss'],
})
export class AddNewSectionComponentImpl extends AddNewSectionComponent {

  form: FormVO;

  constructor(private injector: Injector, @Inject(MAT_DIALOG_DATA) data: any) {
    super(injector);
    this.form = data?.form;
  }

  beforeOnInit(form: AddNewSectionVarsForm): AddNewSectionVarsForm {
    return form;
  }

  afterOnInit() {}

  doNgAfterViewInit() {
    this.formSectionControl.patchValue({form: this.form});
  }

  doNgOnDestroy() {}

  handleFormChanges(change: any) {}

  handleCancelDialog(): void {}

  handleDialogDone(data: any): any {
    return data;
  }

  afterSetAddNewSectionVarsForm(form: AddNewSectionVarsForm): void {}
  handleFormSectionFormAddDialog(): void {
  }

  handleFormSectionFormSearch(): void {
  }

  handleFormSectionFormSelected(event: MatRadioChange, data: FormVO): void {
  }

  handleFormSectionFormFieldsAddDialog(): void {
  }

  handleFormSectionFormFieldsSearch(): void {
  }
  
  handleFormSectionFormFieldsSelected(event: MatCheckboxChange, data: FormFieldVO): void {
  }
}
