// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector, Inject } from '@angular/core';
import { EditLicenseeComponent } from '@app/view/form/edit-licensee.component';
import { EditLicenseeVarsForm } from '@app/view/form/edit-licensee.component';
import { FormState } from '@app/store/form/form.state';
import * as LicenseeSelectors from '@app/store/licensee/licensee.selectors';
import * as LicenseeActions from '@app/store/licensee/licensee.actions';
import * as FormSelectors from '@app/store/form/form.selectors';
import * as FormActions from '@app/store/form/form.actions';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { MAT_DIALOG_DATA } from '@angular/material/dialog';
import { select } from '@ngrx/store';
import { LicenseeCriteria } from '@app/model/bw/org/bocra/portal/licensee/licensee-criteria';
import { FormCriteria } from '@app/model/bw/org/bocra/portal/form/form-criteria';

@Component({
  selector: 'app-edit-licensee',
  templateUrl: './edit-licensee.component.html',
  styleUrls: ['./edit-licensee.component.scss'],
})
export class EditLicenseeComponentImpl extends EditLicenseeComponent {
  constructor(@Inject(MAT_DIALOG_DATA) data: any, private injector: Injector) {
    super(data, injector);
    this.licenseeFormForms$ = this.store.pipe(select(FormSelectors.selectForms));
    this.licenseeFormLicensees$ = this.store.pipe(select(LicenseeSelectors.selectLicensees));
  }

  override beforeOnInit(form: EditLicenseeVarsForm): EditLicenseeVarsForm {
    return form;
  }
  doNgOnDestroy(): void {}

  override licenseeFormFormSearch() {
    let criteria: FormCriteria = new FormCriteria();
    criteria.code = this.licenseeFormFormSearchField.value;
    criteria.formName = this.licenseeFormFormSearchField.value;
    criteria.licenceTypeId = this.licenseeFormFormSearchField.value;
    this.store.dispatch(
      FormActions.searchForms({
        criteria: criteria,
        loading: true,
      })
    );
  }

  override licenseeFormLicenseeSearch(): void {
    let criteria: LicenseeCriteria = new LicenseeCriteria();
    criteria.licenseeName = this.licenseeFormLicenseeSearchField.value;
    criteria.uin = this.licenseeFormLicenseeSearchField.value;
    this.store.dispatch(
      LicenseeActions.search({
        criteria: criteria,
        loading: true,
      })
    );
  }
}
