// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Inject, Injector } from '@angular/core';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { MAT_DIALOG_DATA } from '@angular/material/dialog';
import { MatRadioChange } from '@angular/material/radio';
import * as FormActions from '@app/store/form/form.actions';
import * as FormSelectors from '@app/store/form/form.selectors';
import { FormState } from '@app/store/form/form.state';
import { EditSectionComponent, EditSectionVarsForm } from '@app/view/form/edit-section.component';
import { FormSectionVO } from '@model/bw/org/bocra/portal/form/section/form-section-vo';

@Component({
  selector: 'app-edit-section',
  templateUrl: './edit-section.component.html',
  styleUrls: ['./edit-section.component.scss']
})
export class EditSectionComponentImpl extends EditSectionComponent {

    constructor(@Inject(MAT_DIALOG_DATA) data: any, private injector: Injector) {
        super(data, injector);
    }

    override beforeOnInit(form: EditSectionVarsForm): EditSectionVarsForm { 
        console.log(this.useCaseScope.pageVariables)

        if(this.useCaseScope.pageVariables['formSection']) {
            form.formSection = this.useCaseScope.pageVariables['formSection'];
        } else {

            if(!form?.formSection) {
                form.formSection = new FormSectionVO();
            }
            form.formSection.form = this.dialogData?.form; 
        }

        return form;
    }
	
    override doNgOnDestroy(){}
}