// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable, Injector } from '@angular/core';
import { SubmissionProcessing } from '@app/controller/form/processing/submission-processing';


@Injectable()
export class SubmissionProcessingImpl extends SubmissionProcessing {

    constructor(private injector: Injector) {
        super(injector);
    }

	public doInitialiseProcessingScreen(form: any): void {
	}

	public doLoadData(form: any): void {
	}

	public doMySubmissions(form: any): void {
	}

	public doAllSubmissions(form: any): void {
	}

	public doOverdueSubmissions(form: any): void {
	}

	public doReturnedSubmissions(form: any): void {
	}

	public doDraftSubmissions(form: any): void {
	}

	public doNewSubmissions(form: any): void {
	}

	public doAcceptedSubmissions(form: any): void {
	}

}
