// Generated by andromda-angular cartridge (app\usecase\state.store.ts.vsl) DO NOT EDIT
import { DocumentVO } from '@app/model/bw/org/bocra/portal/document/document-vo';

export const documentKey = "document";

export interface DocumentState {
    document: DocumentVO | any,
    criteria: String | any,
    id: number | any,
    documents: Array<DocumentVO> | Array<any>,
    removed: boolean,
    sucess: boolean;
    loading: boolean;
    error: any
}

export const initialState: DocumentState = {
    document: null,
    criteria: null,
    id: null,
    documents: [],
    removed: false,
    sucess: false,
    loading: false,
    error: null
};