// Generated by andromda-jsf cartridge (view\table\table.component.impl.ts.vsl)
import { Component, Injector } from '@angular/core';
import { SearchAccessPointsAccessPointsComponent } from '@app/view/access/search-access-points-access-points.component';

@Component({
  selector: 'search-access-points-access-points',
  templateUrl: './search-access-points-access-points.component.html',
  styleUrls: ['./search-access-points-access-points.component.scss'],
})
export class SearchAccessPointsAccessPointsComponentImpl extends SearchAccessPointsAccessPointsComponent {
  constructor(private injector: Injector) {
    super(injector);
  }

  override doSearchAccessPointsEdit(form: any): any {
    return form;
  }
}
