// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { SearchLicencesComponent } from '@app/view/licence/search-licences.component';
import { SearchLicencesSearchForm } from '@app/view/licence/search-licences.component';
import { SearchLicencesVarsForm } from '@app/view/licence/search-licences.component';
import { LicenceState } from '@app/store/licence/licence.state';
import * as LicenceSelectors from '@app/store/licence/licence.selectors';
import * as LicenceActions from '@app/store/licence/licence.actions';

@Component({
  selector: 'app-search-licences',
  templateUrl: './search-licences.component.html',
  styleUrls: ['./search-licences.component.scss']
})
export class SearchLicencesComponentImpl extends SearchLicencesComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

    override beforeOnInit(form: SearchLicencesVarsForm): SearchLicencesVarsForm {
      return form;
    }
	
    override doNgOnDestroy(){}

    /**
     * This method may be overwritten
     */
    override beforeSearchLicencesSearch(form: SearchLicencesSearchForm): void {

      this.store.dispatch(LicenceActions.search({
        criteria: form.criteria,
        loading: true
      }));
    }
    
}