// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  bocraportal::backend::bw.org.bocra.portal::form::FormEntryType
 */
export enum FormEntryType {
    /** TODO: Model Documentation for Enumeration Literal SINGLE value "SINGLE" */
    SINGLE = "SINGLE",
    /** TODO: Model Documentation for Enumeration Literal MULTIPLE value "MULTIPLE" */
    MULTIPLE = "MULTIPLE"
}
