// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable, Injector } from '@angular/core';
import { GroupController } from '@app/controller/group/group-controller';


@Injectable()
export class GroupControllerImpl extends GroupController {

    constructor(private injector: Injector) {
        super(injector);
    }

	public doInitialiseEditScreen(form: any): void {
	}

	public doClear(form: any): void {
	}

	public doSave(form: any): void {
	}

	public doInitialiseSearchScreen(form: any): void {
	}

	public doSearch(form: any): void {
	}

	public doEditGroup(form: any): void {
	}

}
