// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringService.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.org.bocra.portal.licensee.form;

import bw.org.bocra.portal.form.FormDao;
import bw.org.bocra.portal.form.FormRepository;
import bw.org.bocra.portal.licensee.LicenseeDao;
import bw.org.bocra.portal.licensee.LicenseeRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

@SpringBootTest
public class LicenseeFormServiceTest {

    protected Logger logger = LoggerFactory.getLogger(LicenseeFormServiceTest.class);

    @Autowired
    ApplicationContext context;

    @Autowired
    private JdbcTemplate jdbc;
    
    @Autowired
    private LicenseeFormService licenseeFormService;

    @Autowired
    private LicenseeDao licenseeDao;

    @Autowired
    private LicenseeRepository licenseeRepository;

    @Autowired
    private FormDao formDao;

    @Autowired
    private FormRepository formRepository;

    @Autowired
    private LicenseeFormDao licenseeFormDao;

    @Autowired
    private LicenseeFormRepository licenseeFormRepository;

    @Test
    @DisplayName("Test Find By Id Success")
    public void testFindByIdSuccess() {
        
    }

    @Test
    @DisplayName("Test Find By Id Fail")
    public void testFindByIdFail() {
        
    }

    @Test
    @DisplayName("Test Create Success")
    public void testCreateSuccess() {
        
    }

    @Test
    @DisplayName("Test Create Fail")
    public void testCreateFail() {
        
    }

    @Test
    @DisplayName("Test Remove Success")
    public void testRemoveSuccess() {
        
    }

    @Test
    @DisplayName("Test Remove Fail")
    public void testRemoveFail() {
        
    }

    @Test
    @DisplayName("Test Get All Success")
    public void testGetAllSuccess() {
        
    }

    @Test
    @DisplayName("Test Get All Fail")
    public void testGetAllFail() {
        
    }

    @Test
    @DisplayName("Test Find By Licensee Success")
    public void testFindByLicenseeSuccess() {
        
    }

    @Test
    @DisplayName("Test Find By Licensee Fail")
    public void testFindByLicenseeFail() {
        
    }

    @Test
    @DisplayName("Test Find By Form Success")
    public void testFindByFormSuccess() {
        
    }

    @Test
    @DisplayName("Test Find By Form Fail")
    public void testFindByFormFail() {
        
    }

    @Test
    @DisplayName("Test Update Licensee Success")
    public void testUpdateLicenseeSuccess() {
        
    }

    @Test
    @DisplayName("Test Update Licensee Fail")
    public void testUpdateLicenseeFail() {
        
    }

    @Test
    @DisplayName("Test Update Form Success")
    public void testUpdateFormSuccess() {
        
    }

    @Test
    @DisplayName("Test Update Form Fail")
    public void testUpdateFormFail() {
        
    }

}