// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { EditPeriodConfigComponent } from '@app/view/period/config/edit-period-config.component';
import { EditPeriodConfigSaveForm } from '@app/view/period/config/edit-period-config.component';
import { EditPeriodConfigSearchForm } from '@app/view/period/config/edit-period-config.component';
import { EditPeriodConfigDeleteForm } from '@app/view/period/config/edit-period-config.component';
import { EditPeriodConfigVarsForm } from '@app/view/period/config/edit-period-config.component';

@Component({
  selector: 'app-edit-period-config',
  templateUrl: './edit-period-config.component.html',
  styleUrls: ['./edit-period-config.component.scss']
})
export class EditPeriodConfigComponentImpl extends EditPeriodConfigComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

    beforeOnInit(){
    }
	
    afterOnInit() {
    }

    doNgAfterViewInit() {
    }

    handleFormChanges(change: any) {
    }

    doNgOnDestroy(){}

    /**
     * This method may be overwritten
     */
    afterSetEditPeriodConfigVarsForm(form: EditPeriodConfigVarsForm): void {

    }

    /**
     * This method may be overwritten
     */
    afterSetEditPeriodConfigSaveForm(form: EditPeriodConfigSaveForm): void {

    }

    /**
     * This method may be overwritten
     */
    beforeEditPeriodConfigSave(form: EditPeriodConfigSaveForm): void {

    }

    /**
     * This method may be overwritten
     */
    afterEditPeriodConfigSave(form: EditPeriodConfigSaveForm): void {

    }
    
    /**
     * This method may be overwritten
     */
    afterSetEditPeriodConfigSearchForm(form: EditPeriodConfigSearchForm): void {

    }

    /**
     * This method may be overwritten
     */
    beforeEditPeriodConfigSearch(form: EditPeriodConfigSearchForm): void {

    }

    /**
     * This method may be overwritten
     */
    afterEditPeriodConfigSearch(form: EditPeriodConfigSearchForm): void {

    }
    
    /**
     * This method may be overwritten
     */
    afterSetEditPeriodConfigDeleteForm(form: EditPeriodConfigDeleteForm): void {

    }

    /**
     * This method may be overwritten
     */
    beforeEditPeriodConfigDelete(form: EditPeriodConfigDeleteForm): void {

    }

    /**
     * This method may be overwritten
     */
    afterEditPeriodConfigDelete(form: EditPeriodConfigDeleteForm): void {

    }
    
}