// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { SearchPeriodConfigsComponent } from '@app/view/period/config/search-period-configs.component';
import { SearchPeriodConfigsSearchForm } from '@app/view/period/config/search-period-configs.component';
import { SearchPeriodConfigsVarsForm } from '@app/view/period/config/search-period-configs.component';
import * as PeriodConfigActions from '@app/store/period/config/period-config.actions';

@Component({
  selector: 'app-search-period-configs',
  templateUrl: './search-period-configs.component.html',
  styleUrls: ['./search-period-configs.component.scss']
})
export class SearchPeriodConfigsComponentImpl extends SearchPeriodConfigsComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

    override beforeOnInit(form: SearchPeriodConfigsVarsForm){
        return form;
    }
	
    override doNgOnDestroy(){}

    /**
     * This method may be overwritten
     */
    override beforeSearchPeriodConfigsSearch(form: SearchPeriodConfigsSearchForm): void {

        this.store.dispatch(PeriodConfigActions.search({
            criteria: form.criteria,
            loading: true,
            loaderMessage: 'Searching period configs ...'
        }));
    }    
}