// Generated by andromda-angular cartridge (app\usecase\reducer.store.ts.vsl) DO NOT EDIT
import { Action, createFeature, createReducer, on } from '@ngrx/store';
import * as DocumentTypeActions from './document-type.actions';
import {documentTypeKey, initialState} from './document-type.state';

export const documentTypeReducer = createReducer(
    initialState,
    on(DocumentTypeActions.findByIdSuccess, (state, action) => ({
        ...state,
        documentType: null, 
        documentTypes: [], 
        criteria: null, 
        id: null, 
        success: action.success,
    })),
    on(DocumentTypeActions.saveSuccess, (state, action) => ({
        ...state,
        documentType: null, 
        documentTypes: [], 
        criteria: null, 
        id: null, 
        success: action.success,
    })),
    on(DocumentTypeActions.removeSuccess, (state, action) => ({
        ...state,
        documentType: null, 
        documentTypes: [], 
        criteria: null, 
        id: null, 
        success: action.success,
    })),
    on(DocumentTypeActions.getAllSuccess, (state, action) => ({
        ...state,
        documentType: null, 
        documentTypes: [], 
        criteria: null, 
        id: null, 
        success: action.success,
    })),
    on(DocumentTypeActions.searchSuccess, (state, action) => ({
        ...state,
        documentType: null, 
        documentTypes: [], 
        criteria: null, 
        id: null, 
        success: action.success,
    })),
    on(DocumentTypeActions.getAllPagedSuccess, (state, action) => ({
        ...state,
        documentType: null, 
        documentTypes: [], 
        criteria: null, 
        id: null, 
        success: action.success,
    })),
    on(DocumentTypeActions.documentTypeReset, (state) => ({
      ...state,
        documentType: null, 
        documentTypes: [], 
        criteria: null, 
        id: null, 
        loading: false,
        success: false,
        errors: []
    })),
    on(DocumentTypeActions.documentTypeFailure, (state, action) => ({
        ...state,
        loading: false,
        success: false,
        errors: action.errors
    })),
    on(DocumentTypeActions.documentTypeLoading, (state, action) => ({
        ...state,
        loading: action.loading,
        success: false
    })),
    // on(DocumentTypeActions.documentTypeSuccess, (state, action) => ({
    //     ...state,
    //     loading: action.loading,
    //     success: action.success,
    //     errors: action.errors
    // }))
);

export const documentTypeFeature = createFeature({
    name: documentTypeKey,
    reducer: documentTypeReducer
});
