// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, Injector } from '@angular/core';
import { Observable } from 'rxjs';
import { ContactMessageRestController } from '@app/service/bw/org/bocra/portal/contact/contact-message-rest-controller';
import { ContactMessageVO } from '@app/model/bw/org/bocra/portal/contact/contact-message-vo';

@Injectable()
export class ContactMessageRestControllerImpl extends ContactMessageRestController {

    constructor(private injector: Injector) {
        super(injector);
    }

    public override findById(id: number | any ): Observable<ContactMessageVO | any> {

        return this.http.get<ContactMessageVO | any>(this.path + `/${id}`);

    }

    public override getAll(): Observable<ContactMessageVO[] | any[]> {

        return this.http.get<ContactMessageVO[] | any[]>(this.path + `/all`);

    }

    public override getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<ContactMessageVO[] | any[]> {

        return this.http.get<ContactMessageVO[] | any[]>(this.path + `/page/${pageNumber}/size/${pageSize}`);

    }

    public override remove(id: number | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(this.path + `/${id}`);

    }

    public override save(contactMessage: ContactMessageVO | any ): Observable<ContactMessageVO | any> {

        return this.http.post<ContactMessageVO | any>(this.path, contactMessage);

    }

    public override search(criteria: string | any ): Observable<ContactMessageVO[] | any[]> {

        return this.http.get<ContactMessageVO[] | any[]>(this.path + `/search/criteria/${criteria}`);

    }

}