// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, Injector } from '@angular/core';
import { HttpClient} from '@angular/common/http';
import { Observable } from 'rxjs';
import { AuthController } from '@app/service/bw/org/bocra/portal/auth/auth-controller';

@Injectable()
export class AuthControllerImpl extends AuthController {

    constructor(private injector: Injector) {
        super(injector);
    }

    public signin(username: string, password: string): Observable<Object> {

        let formData: any = new FormData();
        formData.append("username", username)
        formData.append("password", password)
        return this.http.post<Object>(this.path + '/signin', formData);

    }

    public signout(refreshToken: string): Observable<void> {

        let formData: any = new FormData();
        formData.append("refreshToken", refreshToken)
        return this.http.post<void>(this.path + '/signout', formData);

    }

}