// Generated by andromda-angular cartridge (app\usecase\action.store.ts.vsl) DO NOT EDIT
import { createAction, props } from '@ngrx/store';
import { LicenseeVO } from '@app/model/bw/org/bocra/portal/licensee/licensee-vo';
import { LicenseeCriteria } from '@app/model/bw/org/bocra/portal/licensee/licensee-criteria';
import { Documents } from '@app/view/document/documents.component';

export enum LicenseeActionType {
    FIND_BY_ID = '[Licensee] Find By Id',
    FIND_BY_ID_SUCCESS = '[Licensee] Find By Id Success',
    SAVE = '[Licensee] Save',
    SAVE_SUCCESS = '[Licensee] Save Success',
    REMOVE = '[Licensee] Remove',
    REMOVE_SUCCESS = '[Licensee] Remove Success',
    GET_ALL = '[Licensee] Get All',
    GET_ALL_SUCCESS = '[Licensee] Get All Success',
    SEARCH = '[Licensee] Search Licensees',
    SEARCH_SUCCESS = '[Licensee] Search Licensees Success',
    GET_ALL_PAGED = '[Licensee] Get All Paged',
    GET_ALL_PAGED_SUCCESS = '[Licensee] Get All Paged Success',
    GET_DOCUMENTS = '[Licensee] Get Documents',
    GET_DOCUMENTS_SUCCESS = '[Licensee] Get Documents Success',
    LICENSEE_RESET = '[Licensee] Licensee Reset',
    LICENSEE_FAILURE = '[Licensee] Licensee Action Failure'
}

export const findById = createAction(
    LicenseeActionType.FIND_BY_ID,
    props<{ id: number | any  }>()
);

export const findByIdSuccess = createAction(
    LicenseeActionType.FIND_BY_ID_SUCCESS,
    props<{ licensee: LicenseeVO | any }>()
);

export const save = createAction(
    LicenseeActionType.SAVE,
    props<{ licensee: LicenseeVO | any  }>()
);

export const saveSuccess = createAction(
    LicenseeActionType.SAVE_SUCCESS,
    props<{ licensee: LicenseeVO | any }>()
);

export const remove = createAction(
    LicenseeActionType.REMOVE,
    props<{ id: number | any  }>()
);

export const removeSuccess = createAction(
    LicenseeActionType.REMOVE_SUCCESS,
    props<{ removed: boolean | any }>()
);

export const getAll = createAction(
    LicenseeActionType.GET_ALL);

export const getAllSuccess = createAction(
    LicenseeActionType.GET_ALL_SUCCESS,
    props<{ licensees: LicenseeVO[] | any }>()
);

export const search = createAction(
    LicenseeActionType.SEARCH,
    props<{ criteria: LicenseeCriteria | any  }>()
);

export const searchSuccess = createAction(
    LicenseeActionType.SEARCH_SUCCESS,
    props<{ licensees: LicenseeVO[] | any }>()
);

export const getDocuments = createAction(
    LicenseeActionType.GET_DOCUMENTS,
    props<{ licenseeId: number | any  }>()
);

export const getDocumentsSuccess = createAction(
    LicenseeActionType.GET_DOCUMENTS_SUCCESS,
    props<{ documents: Documents[] | any }>()
);

export const getAllPaged = createAction(
    LicenseeActionType.GET_ALL_PAGED,
    props<{ pageNumber: number | any , pageSize: number | any  }>()
);

export const getAllPagedSuccess = createAction(
    LicenseeActionType.GET_ALL_PAGED_SUCCESS,
    props<{ licensees: LicenseeVO[] | any }>()
);

export const licenseeReset = createAction(LicenseeActionType.LICENSEE_RESET);

export const licenseeFailure = createAction(
    LicenseeActionType.LICENSEE_FAILURE,
    props<{ error: any }>()
);
