// Generated by andromda-angular cartridge (app\usecase\action.store.ts.vsl) DO NOT EDIT
import { Injectable } from '@angular/core';
import { LicenseeRestControllerImpl } from '@app/service/bw/org/bocra/portal/licensee/licensee-rest-controller.impl';
import { Actions, createEffect, ofType } from '@ngrx/effects';
import { catchError, map, mergeMap } from 'rxjs';
import * as LicenseeActions from './licensee.action';

@Injectable()
export class LicenseeEffects {
  constructor(private actions$: Actions, private licenseeService: LicenseeRestControllerImpl) {}

  saveGroup$ = createEffect(() =>
    this.actions$.pipe(
      ofType(LicenseeActions.saveLicensee),
      mergeMap(({ licensee }) =>
        this.licenseeService.save(licensee).pipe(
          map((group) => LicenseeActions.saveLicenseeSuccess({ licensee })),
          catchError(({ error }) => [LicenseeActions.licenseeActionFailure(error)])
        )
      )
    )
  );

  findById$ = createEffect(() =>
    this.actions$.pipe(
      ofType(LicenseeActions.findById),
      mergeMap(({ id }) =>
        this.licenseeService.findById(id).pipe(
          map((licensee) => LicenseeActions.findByIdSuccess({ licensee })),
          catchError(({ error }) => [LicenseeActions.licenseeActionFailure(error)])
        )
      )
    )
  );

  loadAll$ = createEffect(() =>
    this.actions$.pipe(
      ofType(LicenseeActions.loadAll),
      mergeMap(() =>
        this.licenseeService.getAll().pipe(
          map((licensees) => LicenseeActions.loadAllSuccess({ licensees })),
          catchError(({ error }) => [LicenseeActions.licenseeActionFailure(error)])
        )
      )
    )
  );

  searchLicensees$ = createEffect(() =>
    this.actions$.pipe(
        ofType(LicenseeActions.searchLicensees),
        mergeMap(({searchCriteria}) => 
            this.licenseeService.searchLicensees(searchCriteria).pipe(
                map((licensees) => LicenseeActions.searchLicenseesSuccess({licensees})),
                catchError(({ error }) => [LicenseeActions.licenseeActionFailure(error)])
            )
        )
    )
  );
}
