// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, Injector } from '@angular/core';
import { HttpClient} from '@angular/common/http';
import { Observable } from 'rxjs';
import { SimRestController } from '@app/service/bw/org/bocra/portal/form/sim/sim-rest-controller';
import { KpiVO } from '@app/model/bw/org/bocra/portal/form/kpi/kpi-vo';
import { SimVO } from '@app/model/bw/org/bocra/portal/form/sim/sim-vo';
import { FormCriteria } from '@app/model/bw/org/bocra/portal/form/form-criteria';

@Injectable()
export class SimRestControllerImpl extends SimRestController {

    constructor(private injector: Injector) {
        super(injector);
    }

    public findById(id: number): Observable<KpiVO> {

        return this.http.get<KpiVO>(this.path + `/id/${id}`);

    }

    public getAll(): Observable<SimVO[]> {

        return this.http.get<SimVO[]>(this.path + `/all`);

    }

    public remove(id: number): Observable<boolean> {

        return this.http.delete<boolean>(this.path + `/id/${id}`);

    }

    public save(simVO: SimVO): Observable<SimVO> {

        return this.http.post<SimVO>(this.path, simVO);

    }

    public search(searchCriteria: FormCriteria): Observable<SimVO[]> {

        return this.http.post<SimVO[]>(this.path + `/search`, searchCriteria);

    }

}