// Generated by andromda-angular cartridge (view\use-case.module.ts.vsl) DO NOT EDIT
import { NgModule } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { FlexLayoutModule } from '@angular/flex-layout';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { SharedModule } from '@shared';
import { CsvModule } from '@ctrl/ngx-csv';
import { MaterialModule } from '@app/material.module';
import { FormActivationRoutingModule } from './form-activation-routing.module';
import { EditFormActivationComponentImpl } from '@app/view/form/activation/edit-form-activation.component.impl';
import { SearchFormActivationsComponentImpl } from '@app/view/form/activation/search-form-activations.component.impl';
import { SearchFormActivationsFormActivationsComponentImpl } from '@app/view/form/activation/search-form-activations-form-activations.component.impl'; // 2
import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';
import { formActivationFeature } from '@app/store/form/activation/form-activation.reducers';
import { FormActivationEffects } from '@app/store/form/activation/form-activation.effects';
import { FormActivationControllerImpl } from '@app/controller/form/activation/form-activation-controller.impl';
import { LicenseeFormRestController } from '@app/service/bw/org/bocra/portal/licensee/form/licensee-form-rest-controller';
import { LicenseeSectorRestController } from '@app/service/bw/org/bocra/portal/licensee/sector/licensee-sector-rest-controller';
import { FormActivationRestController } from '@app/service/bw/org/bocra/portal/form/activation/form-activation-rest-controller';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    FlexLayoutModule,
    MaterialModule,
    CsvModule,
    FormActivationRoutingModule,
    StoreModule.forFeature(formActivationFeature),
    EffectsModule.forFeature([FormActivationEffects]),
  ],
  declarations: [
    EditFormActivationComponentImpl,
    SearchFormActivationsComponentImpl,
    SearchFormActivationsFormActivationsComponentImpl,
  ],
  entryComponents: [],
  providers: [
    FormActivationControllerImpl,
    LicenseeFormRestController,
    LicenseeSectorRestController,
    FormActivationRestController,
    DatePipe,
  ],
})
export class FormActivationModule {}
