// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { SearchFormActivationsComponent } from '@app/view/form/activation/search-form-activations.component';
import { SearchFormActivationsSearchForm } from '@app/view/form/activation/search-form-activations.component';
import { SearchFormActivationsVarsForm } from '@app/view/form/activation/search-form-activations.component';
import * as FormActivationActions from '@app/store/form/activation/form-activation.actions';
import { FormActivationCriteria } from '@app/model/bw/org/bocra/portal/form/activation/form-activation-criteria';

@Component({
  selector: 'app-search-form-activations',
  templateUrl: './search-form-activations.component.html',
  styleUrls: ['./search-form-activations.component.scss'],
})
export class SearchFormActivationsComponentImpl extends SearchFormActivationsComponent {
  constructor(private injector: Injector) {
    super(injector);
  }

  override beforeOnInit(form: SearchFormActivationsVarsForm): SearchFormActivationsVarsForm {
    return form;
  }

  doNgOnDestroy(): void {}

  override beforeSearchFormActivationsSearch(form: SearchFormActivationsSearchForm): void {
    let criteria: FormActivationCriteria = new FormActivationCriteria();
    criteria.activationName = form.activationName;

    this.searchFormActivationsFormActivationsComponent.criteria = criteria;
    this.searchFormActivationsFormActivationsComponent.formActivationsPaginator.pageIndex = 0

    this.store.dispatch(
      FormActivationActions.pagedSearch({
        pageNumber: this.searchFormActivationsFormActivationsComponent.formActivationsPaginator.pageIndex + 1,
        pageSize: this.searchFormActivationsFormActivationsComponent.formActivationsPaginator.pageSize,
        criteria: criteria,
        loading: true,
        loaderMessage: 'Searching form activations ...',
      })
    );
  }
}
